### ISSUE TITLE
[Chapter 07] 음악 랜덤 플레이

### ISSUE THREAD

**Issue by Fruitson82** [Develothy/Java17Basic#1]
### 설명
- 플레이리스트에 있는 10개의 음악을 랜덤으로 20번 플레이하도록 한다.
- 한 번 재생된 음악은 재생 후 3번 안에 플레이되면 안된다. 
  - 예. 첫번째 A 플레이 이후, 두번째, 세번째, 네번째에는 A가 플레이 되면 안됨.
- 10개의 음악은 최초에 자유롭게 셋팅하도록 한다.
- 플레이는 화면(콘솔)에 음악명을 찍는 것으로 대체한다.
- (필수) 해당 결과는 IDE(Intellij, VSCode...)가 아닌 Command로 실행 가능하도록 한다.

### 출력 예시
```
[1] A.mp3
[2] D.mp3
[3] E.mp3
...
[20] A.mp3
```

**Comment by Develothy** [comment]
#음악 랜덤플레이 미션을 진행하면서 asList에 대해 가볍게 정리해봤습니다 ~ 🎶 🎧 
[#asList](https://develothy.notion.site/ArrayList-asList-77ac9c0464314ea797e26390e279dcd1)

**Comment by Fruitson82** [comment]
추가로 아래 내용도 확인 부탁해요~

- 왜 list를 선언할 때 ArrayList로 선언했을까?
- asList로 객체를 생성 시 return을 new ArrayList로 생성하는데 remove 메서드가 동작을 안할까?
- 좀 더 리펙토링을 해보자.

**Comment by Develothy** [comment]
오 알아보면서 새로운 사실을 발견했습니다 !

- asList로 객체를 생성 시 ArrayList를 리턴하는데  add, remove가 작동하지 않는 이유는! 
이때 리턴되는 ArrayList가 Arrays의 이너클래스인 ArrayList 였습니다!! Arrays에서 고정 크기의 동일한 타입의 데이터 집합 배열을 가진 리스트를 리턴하기 때문에 크기 변경 동작이 작동하지 않았습니다.
[#Arrays.ArrayList](https://develothy.notion.site/asList-return-ArrayList-77ac9c0464314ea797e26390e279dcd1)

- ArrayList 사용시 List를 선언하는 이유는 처음부터 변경에 유연한 구조로 미리 설계하는 것 같아요. 언젠가 이 ArrayList가 LinkedList로 변경되어도 선언부만 변경하면 되고,, hashMap도 Map으로 선언하는게 비슷한 이유에서 그랬을 것 같네요,,
[ArrayList는 왜 List로 선언할까?](https://develothy.notion.site/List-ArrayList-00fa949e367b41449b11ec126058b19c)

**Comment by Fruitson82** [comment]
추가로..

1. List와 Map의 차이
2. List와 Map의 검색 방식의 차이

를 한번 찾아보면 좋을것 같아요.

**Comment by Develothy** [comment]
알아보며 놀라운 사실을 발견했습니다. Map이 더 빠르다니,,, 당연히 index를 갖고있는 list가 더 빠를 것이라고 생각했는데, Map또한 key를 인덱스로 변환하여 찾고 있었군요,, list는 순회하고 Map은 map 종류별로 다양한 접근방법에 대해 알아보면서 재밌었습니다 😄 

[#List와 Map의 차이](https://develothy.notion.site/List-Map-3c9efc8262ad4345b0419cf63a9722d3)

**Comment by Fruitson82** [comment]
오~ 늦은시간까지... 👍
