### ISSUE TITLE
Java 파일을 Command로 실행해보기

### ISSUE THREAD

**Issue by Fruitson82** [Develothy/Java17Basic#3]
### 설명
- 작성한 Java 파일을 IDE(Intellij, VSCode...)를 사용하지 않고 실행해본다.
- 실행까지의 과정을 정리해본다. (디테일할수록 좋다.)

**Comment by Develothy** [comment]
완료하였습니다!! 미션을 수행하면서 알게된 것들에 대해 정리해보았습니다..[#java command](https://develothy.notion.site/Java-7df30d21897542c9917882c1264538e9)

<img width="395" alt="Screenshot 2023-02-20 at 2 36 10 AM" src="https://user-images.githubusercontent.com/94438006/219964892-517f8309-4bff-4458-b149-e10f610fcb04.png">
