### ISSUE TITLE
ClassLoader를 한번 찾아보자!

### ISSUE THREAD

**Issue by Fruitson82** [Develothy/Java17Basic#5]
Java ClassLoader에 대해서 한번 찾아보자!

**Comment by Develothy** [comment]
JVM에서도 컴파일된 클래스파일을 실행하기 위한 과정들이 필요하군요 👍 
가볍게 정리해보았습니다 [#JVM_ClassLoader](https://develothy.notion.site/JVM-f69f95fb3e514e809ab0ecbd6aefc239)

**Comment by Fruitson82** [comment]
Main Class를 호출 시 호출하기까지 로딩되는 Class를 찍어보면 좋을것 같아요~

**Comment by Develothy** [comment]
`-verbose:class` 옵션을 추가하면 로딩되는 class도 찍어주는데 상당히 많네요,,! java에서도 getClassLoader로 현재 classloader가 확인가능하네욥!

`❯ java -verbose:class basic.Basic17Application
[Opened /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar]
[Loaded java.lang.Object from /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar]
[Loaded java.io.Serializable from /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar]
[Loaded java.lang.Comparable from /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar]`
이하 생략....
